[project]
name = "python-pdf-linker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymupdf>=1.26.6",
    "pyyaml>=6.0.3",
]
